# -*- coding: utf-8 -*-
"""Practica9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDdmN5OOsdApeZ4-1CtDlWf0s1IIBSFl
"""

!pip install wordcloud

"""# Carga de dataset y librerias"""

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

df = pd.read_csv('Reviews.csv')
df.head()

df.info()

df.dropna(subset= ['Text', 'Score'], inplace = True)

"""# Creación de WordCloud para cada valor de score

El dataset elegido tiene reseñas a comidas de Amazon con puntaje incluido, registradas a lo largo de 10 años, empezando desde el 2012
"""

df['Score'].unique()

"""Hay solo 5 tipos diferentes de valores para el puntaje dado a una reseña. Para observar las palabras más usadas en cada puntaje se creará un wordcloud para cada uno de los puntajes"""

df.columns

plt.figure(figsize=(30, 20))

for i in range(1,6):

  df_score = df[df['Score'] == i]

  text = " ".join(df_score["Text"])


  cloud = WordCloud(
      width=800,
      height=400,
      background_color="white",
      colormap="viridis"
  ).generate(text)

  plt.subplot(2, 3, i)
  plt.imshow(cloud, interpolation="bilinear")
  plt.title(f"Wordcloud para puntaje {i}")

  plt.axis("off")

"""Para empezar, en todas se repiten las palabras br mucho, ya que estás son palabras claves utilizadas para indicar un salto de línea.

Por otro lado, en todas se repiten muchas palabras relacionadas a la comida:  "flavor", "taste" o "food", lo cual corrabora el hecho de que el dataset utilizada es sobre reseñas de comidas. Además, el café parece ser un producto muy comprado o reseñado dentro del dataset, al destacar en todos los tipos de puntuación. Esto puede indicar que usualemente se compra café online, si es que los datos fueron obtenidos de forma aleatoria.

Lo primero a resaltar de los resultados es observar que cuando el puntaje es de 5, sí hay palabras muy frecuentes relacionadas a una puntuación alta como "love", "good" o "great"; además que suelen ser más frecuentes en opiniones con puntuaciones altas que en puntuaciones bajas.

En contraste, la nube de palabras para las reseñas con la peor puntuación, 1, destaca la palabra "will", "buy" y "Amazon" en comparación con las demás nubes. La primera y segunda palabras pueden indicar que muchas veces que el producto era malo, el consumidor se ve obligado a hacer una acción aparte, como devoluciones, quejas o directamente decir que no compraría de nuevo el producto. La tercera palabra, "Amazon", puede indicar que muchas de las quejas iban dirigidas a Amazon, o sea problemas directamente con la entrega de productos, que es en sí el trabajo de Amazon. Por último, la palabra "dog" destaca de entre las demás, indicando las siguientes dos cosas: Hubo problemas con los perros de los dueños al momento de ingerir la comida, o dentro del dataset se incluye la venta de comida de perro, la cual suele ser mal evaluada.


"""

