# -*- coding: utf-8 -*-
"""Practica4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYpqCL88EA-i6jSiymKcvulYG2uIFMTa

# Carga de datos e importación de librerias
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import kruskal

df = pd.read_csv('avocado_clean.csv')
df['Date'] = pd.to_datetime(df['Date'])

"""Para no sesgar las pruebas de hipótesis, únicamente se analizaran el valor del valor promedio del aguacate para el grupo "convencional" y para el grupo "orgánico"

# Separación de dataset entorno a Labels y determinación de cumplimiento del supuesto de normalidad
"""

df['type'].unique()

organic_avg_price = df[df['type'] == 'organic'].loc[:,'AveragePrice']
conventional_avg_price = df[df['type'] == 'conventional'].loc[:,'AveragePrice']

"""Supuesto de normalidad (mediante el test de D’Agostino y Pearson)

Se debe comprabar si los campos a comparar cumplen con el supuesto de normalidad para aplicar ANOVA, en caso contrario se aplicará el test de kruskall wallis.
"""

#Para todos los labels de type


import scipy.stats as stats


#organic


results = stats.normaltest(organic_avg_price)
print('Precio promedio de aguacates convecionales')
print(f'Estadístico: {results.statistic}\nvalor p: {results.pvalue}')

#Conventional

print('Precio promedio de aguacates orgánicos')
results = stats.normaltest(conventional_avg_price)
print(f'Estadístico: {results.statistic}\nvalor p: {results.pvalue}')

"""Considerando un nivel de significancia de α = 0.05, se puede concluir que el precio promedio de los aguacates promedios sí se distribuye de forma normal. Sin embargo, esto no se cumple para el precio promedio de aguacates orgánicos, o sea, no cumple el criterio de normalidad. Esto significa que no podemos aplicar un ANOVA al conjunto de datos a analizar.

Por ende, se aplicará el test de Kruskall Wallis para la comparación de distribuciones.

# Aplicación del test Kruskall Wallis
"""

from scipy.stats import kruskal

#Para la columna type

stat, p= kruskal(organic_avg_price,conventional_avg_price)

print('Prueba de Kruskall Wallis')
print('Comparación entre las distribuciones de precio promedio de aguacates convencionales y orgánicos')
print(f'Estadístico: {stat}\nvalor p: {p}')

"""con un nivel de significancia de α = 0.05, como el p valor es menor a α, se puede concluir ambas distribuciones son diferentes.

Esto implica que el precio promedio de los aguacates convencionales se distribuye de forma diferente al precio promedio de los aguacates orgánicos.

Se puede concluir que el precio promedio del aguacate si puede agregar información importante a un modelo, al momento de intentar predecir el tipo del aguacate vendido.
"""