# -*- coding: utf-8 -*-
"""Practica5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElJQ7K84KqB8Bl_I0Ts-aWOZ1nN5Cobu

# Carga de librerias y dataframe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

df = pd.read_csv('avocado_clean.csv')

df['Date'] = df['Date'].astype('datetime64[ns]')

"""# Correlaciones entre variables

Antes de empezar, para esta actividad se excluyó la columna de regiones ('region') debido a contiene demasiados valores como para analizarlos visualmente. Además, la correlación utilizando cada region suele ser baja (0.0 - 0.2) para cada variable, por lo que incluirlas solo afectaría los resultados.
"""

df_dummies.head()

df_dummies = pd.get_dummies(df, columns=['type'], drop_first=True)

correlation_matrix = df_dummies.drop(['Date', 'region'], axis=1).corr()
plt.figure(figsize=(12, 10))
sn.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix (Excluding Date and Region)')
plt.show()

"""Para empezar, se observa que Average price muestra una correlación negativa para todas las variables excepto, type_organic. Esto es de esperarse ya que entre más volumen se haya vendido, lo normal es esperar que sea porque el precio era barato, y viceversa. Para el tipo de aguacate, se observa un valor mayor para aguacates organicos.

Para Total Volume, se observa una gran correlacion entre el volumen vendido de los demás aguacates y bolsas, y una negativa con respecto al tipo de aguacate. De nuevo, aquí se puede observar una clara colinealidad, ya que en si el volumen total es la suma de venta de todos las variades de aguacates (4046, 4225. En este caso, se eliminó anteriormente la variedad 4770). Si el Aguacate es orgánico, se espera un menor volumen de venta (Esto ya se había observado en anteriores actividades)

Para el volumen de venta de aguacate 4046, se observa una correlacion positiva con la variedad 4225, el total de bolsas vendidas y la cantidad de bolsas pequeñas vendidas. Que el total de bolsas vendidas sea directamente proporcional es de esperarse. En cuanto al tipo de aguacate, se tiene un coeficiente negativo.

Parala variante 4225, se observan características similares a las observadas en la variedad 4046.

En cuanto al total de bolsas, la correlación positiva con las bolsas pequeñas es completamente esperado y es colineal. Sin emabargo, el factor de correlación es negativo para el tipo de aguacate.

Por último, se observa una correlación negativa entre la venta de bolsas pequeñas y el tipo orgánico.

Para observar la relación entre las demás variables con el transcurso del tiempo, se obtuvo el promedio obtenido en cada día de cada variable, ya que usualmente hay información repetida cada día para cada región.
"""

daily_avg_df = df.groupby('Date').mean(numeric_only=True).reset_index()
display(daily_avg_df.head())

all_columns_daily = daily_avg_df.columns.tolist()
columns_to_plot_daily = [col for col in all_columns_daily if col != 'Date']
print(columns_to_plot_daily)

for column_name in columns_to_plot_daily:
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.scatter(daily_avg_df['Date'], daily_avg_df[column_name])
    ax.set_title(f'Daily Average of {column_name}')
    ax.set_xlabel('Date')
    ax.set_ylabel(column_name)
    plt.tight_layout()
    plt.show()

"""Se observa que por lo general el volumen de total vendido y para cada variedad de aguacate disminuye conforme pasa el tiempo, o sea se observa una correlación negativa.

Sorprendementemente, se observa un aumento en las ventas totales de bolsas y de solo bolsas pequeñas. Puede indicar que cada vez había menos aguacates en cada una de las bolsas, por lo que la venta de bolsas tuvo que aumentar para compensar dicha diferencia.

No se puede determinar con tanta facilidad, por lo menos de forma visual, la tendencia real del precio promedio de los aguacates: Es complicado saber si tiende a subir o no debido a las grandes variaciones de precios. Por lo menos, se sabe que el precio promedio tuvo un pico a finales de 2017.

# Regresión lineal simple (utilizando como variable dependiente el tiempo)

Se hara una regresión lineal para todas las anteriores variables mostradas
"""

daily_avg_df['Date_numeric'] = daily_avg_df['Date'].astype('int64') // 10**9

all_columns_daily = daily_avg_df.columns.tolist()
dependent_variables = [col for col in all_columns_daily if col not in ['Date', 'Date_numeric']]
print(dependent_variables)

import statsmodels.api as sm

dependent_variables = ['AveragePrice', 'Total Volume', '4046', '4225', 'Total Bags', 'Small Bags']

for column_name in dependent_variables:
    print(f"\nPerforming linear regression for: {column_name}")

    # Define independent and dependent variables
    X = daily_avg_df['Date_numeric']
    y = daily_avg_df[column_name]

    # Add a constant to the independent variable
    X = sm.add_constant(X)

    # Create and fit the OLS model
    model = sm.OLS(y, X)
    results = model.fit()

    # Print the regression results
    print(results.summary())

    # Plotting the results
    plt.figure(figsize=(12, 6))
    plt.scatter(daily_avg_df['Date'], y, label='Original Data', s=10)
    plt.plot(daily_avg_df['Date'], results.predict(X), color='red', label='Fitted Line')
    plt.title(f'Linear Regression of {column_name} vs. Date')
    plt.xlabel('Date')
    plt.ylabel(column_name)
    plt.legend()
    plt.show()

"""Analizanado el valor de las R^2 de cada regresión, se puede concluir que solo las últimas cuatro muestran una fuerte dependencia lineal en torno al tiempo, al tener valores de R^2 mayores a 0.4."""