# -*- coding: utf-8 -*-
"""Practica1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EaXTIoPOeKfJOBZ_J70f5eHncdfloGj

# Carga de librerías y dataset
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import kagglehub

# Download latest version
path = kagglehub.dataset_download("neuromusic/avocado-prices")

print("Path to dataset files:", path)

"""Cambios a realizar

- Normalización, estandarización, log transform
"""

df = pd.read_csv(path + "/avocado.csv")

df.head()

"""La columnas 'Unnamed: 0' y 'year' no son necesarias"""

df.drop(['Unnamed: 0', 'year'], axis = 1, inplace=True)

"""# Imputación de valores varios"""

df.info()

"""Se observa que no hay valores nulos, por lo que no se realiza ningún cambio

# Transformación de datos
"""

df.info()

"""El tipo de valor de la fecha debería de ser de tipo datetime"""

df['Date'] = pd.to_datetime(df['Date'])

df.info()

"""# Detección y eliminación de valores atípicos"""

df.head()

numerical_columns = df.select_dtypes(include=['number']).columns

for column in numerical_columns:
  sns.scatterplot(x='AveragePrice', y =column, data=df)
  plt.show()

"""Una estadística que podría aportar información importante inclusive si es un valor atípico es el precio promedio del aguacate, ya que, por conocimiento básico de mercado, se sabe que a mayor demanda, mayor el precio del producto, y viceversa.Con estas gráficas se observa que, si bien la cantidad vendida de bolsas de aguacate y volumen vendido si depende de el precio promedio del aguacate (para valores muy altos, directamente no se vende), la información más significativa parece estar conglomerada en donde la mayoría de puntos se encuentran. Entonces, se aplicará de igual forma el método IQR para limpiar los datos atípicos del precio promedio.

Método IQR
"""

numerical_columns = df.select_dtypes(include=['number']).columns

for column in numerical_columns:
  sns.catplot(x=column, kind="box", data=df)

"""Se observan muchos valores atípicos en todos los valores numéricos

Eliminación de valores atípicos
"""

df_aux = df.copy()

for column in numerical_columns:
  Q1 = df_aux[column].quantile(0.25)
  Q3 = df_aux[column].quantile(0.75)
  IQR = Q3 - Q1

  fences = [Q1 - IQR*1.5, Q3 + IQR*1.5]

  df_aux = df_aux[(df_aux[column] >= fences[0]) & (df_aux[column] <= fences[1])]

numerical_columns = df.select_dtypes(include=['number']).columns

for column in numerical_columns:
  sns.scatterplot(x='AveragePrice', y =column, data=df_aux)
  plt.show()

numerical_columns = df.select_dtypes(include=['number']).columns

for column in numerical_columns:
  sns.catplot(x=column, kind="box", data=df)

display(df_aux['Total Volume'].describe())
display(df_aux['4046'].describe())
display(df_aux['4225'].describe())
display(df_aux['4770'].describe())
display(df_aux['Total Bags'].describe())
display(df_aux['Small Bags'].describe())
display(df_aux['Large Bags'].describe())
display(df_aux['XLarge Bags'].describe())

"""Después de la eliminación de valores atípicos, se observa que la columna 'XLarge Bags' ya no es necesaria. Básicamente la mayoría de valores en dicha variable eran 0, por lo que se eliminó cualquier otro que no fuese 0. Las columnas '4770' y 'Large Bags' podrían ser removidas, ya que una tiene la mitad de valores como cero, y la otra tiene un cuarto de valores como 0, respectivamente. Esto puede implicar que desde el inicio sus datos eran en su mayoría 0. Se puede volver a hacer el proceso de IQR con el dataset original sin estas columnas para eliminar menos valores."""

df_aux = df.copy()

df_aux.drop(['XLarge Bags', '4770', 'Large Bags'], axis = 1, inplace=True)
numerical_columns = df_aux.select_dtypes(include=['number']).columns

for column in numerical_columns:
  Q1 = df_aux[column].quantile(0.25)
  Q3 = df_aux[column].quantile(0.75)
  IQR = Q3 - Q1

  fences = [Q1 - IQR*1.5, Q3 + IQR*1.5]

  df_aux = df_aux[(df_aux[column] >= fences[0]) & (df_aux[column] <= fences[1])]

numerical_columns = df_aux.select_dtypes(include=['number']).columns

for column in numerical_columns:
  sns.scatterplot(x='AveragePrice', y =column, data=df_aux)
  plt.show()

numerical_columns = df_aux.select_dtypes(include=['number']).columns

for column in numerical_columns:
  sns.catplot(x=column, kind="box", data=df_aux)

display(df_aux['Total Volume'].describe())
display(df_aux['4046'].describe())
display(df_aux['4225'].describe())
display(df_aux['Total Bags'].describe())
display(df_aux['Small Bags'].describe())

"""En general, se obtuvieron mejores resultados al eliminar dichas columnas"""

df = df_aux.copy()

"""# Transformación de datos (Estandarización)"""

df.describe()

"""Debido a la gran diferencia entre los valores de volumen y precio promedio, se estandarizaran cada una de las columnas numéricas del dataset. Aun así, se crearan dos datasets en formato .csv: Uno sin estandarizar y otro estandarizado en caso de ser necesario el original."""

df_estandar = df.copy()

numerical_columns = df_estandar.select_dtypes(include=['number']).columns


for column in numerical_columns:

  min_value = df_estandar[column].min()
  max_value = df_estandar[column].max()
  df_estandar[column] = (df_estandar[column] - min_value) / (max_value - min_value)

df_estandar.describe()

"""#Guardado de ambos datasets"""

df.head()

df.to_csv('avocado_clean.csv', index=False)
df_estandar.to_csv('avocado_standarized.csv', index=False)

"""#"""