# -*- coding: utf-8 -*-
"""Practica8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtuvX_07KgcwMmWmJTyHmy8vTWaMbwry

# Carga de librerias y dataframe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

df = pd.read_csv('avocado_clean.csv')

df['Date'] = df['Date'].astype('datetime64[ns]')

"""# Regresión lineal simple (utilizando como variable dependiente el tiempo)"""

daily_avg_df = df.groupby('Date').mean(numeric_only=True).reset_index()
daily_avg_df['Date_numeric'] = daily_avg_df['Date'].astype('int64') // 10**9

all_columns_daily = daily_avg_df.columns.tolist()
dependent_variables = [col for col in all_columns_daily if col not in ['Date', 'Date_numeric']]
print(dependent_variables)

import statsmodels.api as sm

dependent_variables = ['AveragePrice', 'Total Volume', '4046', '4225', 'Total Bags', 'Small Bags']

for column_name in dependent_variables:
    print(f"\nPerforming linear regression for: {column_name}")

    # Define independent and dependent variables
    X = daily_avg_df['Date_numeric']
    y = daily_avg_df[column_name]

    # Add a constant to the independent variable
    X = sm.add_constant(X)

    # Create and fit the OLS model
    model = sm.OLS(y, X)
    results = model.fit()

    # Print the regression results
    print(results.summary())

    # Plotting the results
    plt.figure(figsize=(12, 6))
    plt.scatter(daily_avg_df['Date'], y, label='Original Data', s=10)
    plt.plot(daily_avg_df['Date'], results.predict(X), color='red', label='Fitted Line')
    plt.title(f'Linear Regression of {column_name} vs. Date')
    plt.xlabel('Date')
    plt.ylabel(column_name)
    plt.legend()
    plt.show()

"""Se observa que por lo general el volumen de total vendido y para cada variedad de aguacate disminuye conforme pasa el tiempo, o sea se observa una correlación negativa.

Sorprendementemente, se observa un aumento en las ventas totales de bolsas y de solo bolsas pequeñas. Puede indicar que cada vez había menos aguacates en cada una de las bolsas, por lo que la venta de bolsas tuvo que aumentar para compensar dicha diferencia.

No se puede determinar con tanta facilidad, por lo menos de forma visual, la tendencia real del precio promedio de los aguacates: Es complicado saber si tiende a subir o no debido a las grandes variaciones de precios. Por lo menos, se sabe que el precio promedio tuvo un pico a finales de 2017.

Analizanado el valor de las R^2 de cada regresión, se puede concluir que solo las últimas cuatro muestran una fuerte dependencia lineal en torno al tiempo, al tener valores de R^2 mayores a 0.4.
"""