# -*- coding: utf-8 -*-
"""códigoPIA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bdeZLlNJux2EDclmCSHIIKsSiyLgtqJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

df = pd.read_csv('avocado_clean.csv')

df['Date'] = df['Date'].astype('datetime64[ns]')

daily_avg_df = df.groupby('Date').mean(numeric_only=True).reset_index()
display(daily_avg_df.head())

all_columns_daily = daily_avg_df.columns.tolist()
columns_to_plot_daily = [col for col in all_columns_daily if col != 'Date']
print(columns_to_plot_daily)

"""# Regresión lineal simple (utilizando como variable dependiente el tiempo)

Se hara una regresión lineal para todas las anteriores variables mostradas
"""

daily_avg_df['Date_numeric'] = daily_avg_df['Date'].astype('int64') // 10**9

all_columns_daily = daily_avg_df.columns.tolist()
dependent_variables = [col for col in all_columns_daily if col not in ['Date', 'Date_numeric']]
print(dependent_variables)

import statsmodels.api as sm

dependent_variables = ['AveragePrice', 'Total Volume', '4046', '4225', 'Total Bags', 'Small Bags']

for column_name in dependent_variables:
    print(f"\nPerforming linear regression for: {column_name}")

    # Define independent and dependent variables
    X = daily_avg_df['Date_numeric']
    y = daily_avg_df[column_name]

    # Add a constant to the independent variable
    X = sm.add_constant(X)

    # Create and fit the OLS model
    model = sm.OLS(y, X)
    results = model.fit()

    # Print the regression results
    print(results.summary())

    # Plotting the results
    plt.figure(figsize=(12, 6))
    plt.scatter(daily_avg_df['Date'], y, label='Original Data', s=10)
    plt.plot(daily_avg_df['Date'], results.predict(X), color='red', label='Fitted Line')
    plt.title(f'Linear Regression of {column_name} vs. Date')
    plt.xlabel('Date')
    plt.ylabel(column_name)
    plt.legend()
    plt.show()

"""## Top 10 precios más altos y bajos de precio promedio del aguacate orgánico"""

lowest_10_regions = average_price_organic_by_region.tail(10)
print("10 Regions with Lowest Average Organic Avocado Price:")
display(lowest_10_regions)


greatest_10_regions = average_price_organic_by_region.head(10)
print("\n10 Regions with Greatest Average Organic Avocado Price:")
display(greatest_10_regions)