# -*- coding: utf-8 -*-
"""Practica3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KlxxJNJMXkBZFRINTkBUs4zcFR9pJDu

# Cargando las librerías y el dataset
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('avocado_clean.csv')

df['Date'] = pd.to_datetime(df['Date'])

"""# Diagramas de pastel"""

column_categorical = df.select_dtypes(include=['object']).columns

for column in column_categorical:
    value_counts = df[column].value_counts().reset_index()
    labels = value_counts.iloc[:,0]
    values = value_counts.iloc[:,1]



    plt.figure(figsize=(10, 6))
    plt.pie(values, labels=labels, autopct='%1.1f%%', startangle=140)
    plt.title(f'Distribución de {column}')

"""# Histogramas"""

column_numerical = df.select_dtypes(include=['number']).columns

for column in column_numerical:

    plt.figure(figsize=(10, 6))
    plt.hist(df[column], bins=20, density=True)
    plt.title(f'Distribución de {column}')

"""# Diagrama de bigotes"""

aux_df = df.copy()

aux_df = aux_df[aux_df['region'].isin(aux_df['region'].value_counts().reset_index().iloc[:10, 0])]

column_categorical = df.select_dtypes(include=['object']).columns
column_numerical = df.select_dtypes(include=['number']).columns

for n_column in column_numerical:
  for c_column in column_categorical:
    plt.figure(figsize=(20, 10))
    sns.boxplot(data = aux_df, x = c_column, y = n_column)
    plt.title(f'Distribución de {n_column} vs {c_column}')

"""# Gráficos de dispersión (Sin labels categóricos)"""

column_numerical = df.select_dtypes(include=['number']).columns

for n_column_1 in column_numerical:
  for n_column_2 in column_numerical:
    if n_column_1 == n_column_2: continue
    plt.figure(figsize=(10, 5))
    sns.scatterplot(data = df, x = n_column_1, y = n_column_2)
    plt.title(f'Distribución de {n_column_1} vs {n_column_2}')

"""# Gráficos de dispersión (Con datos categóricos)"""

aux_df = df.copy()

aux_df = aux_df[aux_df['region'].isin(aux_df['region'].value_counts().reset_index().iloc[:10, 0])] #Limitar a solo 10 regiones para no hacer un proceso tan largo

column_numerical = df.select_dtypes(include=['number']).columns

for n_column_1 in column_numerical:
  for n_column_2 in column_numerical:
    for c_column in column_categorical:
      if n_column_1 == n_column_2: continue
      plt.figure(figsize=(10, 5))
      sns.scatterplot(data = aux_df, x = n_column_1, y = n_column_2, hue = c_column)
      plt.title(f'Distribución de {n_column_1} vs {n_column_2}')