# -*- coding: utf-8 -*-
"""Practica2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0Ws4IsyVmwDaKBDtGGxlbjQiiyqbPGm

# Cargando las librerias y el dataset a utilizar
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('avocado_clean.csv')

"""# Medidas de tendencia central (Media, Mediana y Moda), Medidas de dispersión(varianza, desviación estándar, rango intercuartílico) y análisis de resultados

Medidas de tendencia central
"""

df.head()

#Media

numerical_columns = df.select_dtypes(include='number').mean()

mean_values = numerical_columns.to_dict()

print("\nMedia\n")
for key, value in mean_values.items():
    print(f"{key}: {value}")


#Mediana

numerical_columns = df.select_dtypes(include='number').median()

median_values = numerical_columns.to_dict()

print("\nMediana\n")
for key, value in median_values.items():
    print(f"{key}: {value}")

#Mode

mode_values = df.mode().loc[:,  ['type', 'region']]

print("\nModa\n")
for key, value in mode_values.items():
    print(f"{key}: {value[0]}")
    print(f"{key}: {value[1]}")

    print(f'veces repetidas: {df[key].value_counts()[value[0]]}')

    print('')

"""medidas de dispersión"""

#Varianza

numerical_columns = df.select_dtypes(include='number').var()

var_values = numerical_columns.to_dict()

print("\nVarianza\n")
for key, value in var_values.items():
    print(f"{key}: {value}")


#Desviación estandar

print("\nDesviación estandar\n")
for key, value in var_values.items():
    print(f"{key}: {value**(1/2)}")


#rango intercuartílico

numerical_columns = df.select_dtypes(include='number')

Q1 = numerical_columns.quantile(0.25)
Q3 = numerical_columns.quantile(0.75)
IQR = Q3 - Q1

print("\nRango intercuartílico\n")
for key, value in IQR.items():
    print(f"{key}: {value}")

"""Analisis de los resultados

El valor más consistente es el precio promedio del aguacate, ya que tanto su media como mediana tienen casi el mismo valor, además que su desviación estándar es relativamente baja (0.36 dolares).

Donde hay ligeros problemas son en los demás datos numéricos:


la media es mayor a la mediana, indicando que hay varios valores muy grandes que afectan el valor de la media. Esto es más evidente al comparar el rango intercuartílico con la mediana de estas mismas variables: Se observa que es una diferencia bastante grande en comparación de las medianas, indicando que los valores cercanos al percentil 75% empiezan a variar demasiado sus valores con respecto a percentiles más bajos.

También se observa una desviación estandar mayor que la media, a veces hasta el doble de grande como en '4046', indicando una gran dispersión en los datos. Esto sucede para las columnas 'Total Volume', '4046', '4225', 'Total Bags' y 'Small Bags'.


En cuanto a las columnas categóricas:


La columna 'type' muestra como moda el valor 'organic' con 8304 repeticiones. Considerando que el dataset tiene 10,000 filas, saber que la mayoría de aguacates son orgánicos nos muestra que el dataset está claramente desbalanceado.

Por otro lado, en cuanto a 'region' tanto Louisville y Syracuse son la moda con 338 repeticiones. En este sentido, el dataset probablemente no esté tan desbalanceado, considerando que hay solo 53 regiones diferentes.
"""